name: Red 62 - Validacion de Infraestructura

on:
  push:
    branches: [ carlin-moker ]
  pull_request:
    branches: [ carlin-moker ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Dependencias
        run: npm install

      - name: Compilacion de Contratos
        run: npx hardhat compile

      - name: Ejecutar Tests
        run: npx hardhat test
      
